[package]
name = "carrot"
version = "0.1.0"
authors = ["Kevin Lydon <klydon@broadinstitute.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Web framework
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-service = "1.0.5"
# Environment variables
dotenv = "0.15.0"
# Logging
env_logger = "0.7.1"
log = "0.4.8"
# DB connection and pooling
diesel = { version = "1.4.3", features = ["postgres", "r2d2", "uuidv07", "chrono"] }
postgres = { version = "0.17.1", features = ["with-uuid-0_8", "with-chrono-0_4"] }
r2d2 = "0.8.8"
# Serializing/Deserializing data
serde = "1.0.104"
serde_json = "1.0.48"
uuid = { version = "0.7", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"]}


